### ISSUE TITLE
Need a configurable timeout on container deployment

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/winc-release#5]
Currently the timeout in winc for brining up the network is hard-coded to 2 seconds:

https://github.com/cloudfoundry/winc/blob/develop/network/netsh/netsh.go#L13

We are seeing frequent timeout errors from this code when deploying containers on Windows Server 2019 due to anti-virus software running on the VM.  It appears to be scanning the filesystem objects and slowing down container operations, and we're unable to modify the AV software configuration due to corporate policy.

We would like to either increase the timeout value on this operation by default (such as 15 seconds), or allow it to be configured via winc-release.  This issue is currently preventing us from deploying Windows Server 2019 cells.

**Comment by amhuber** [comment]
We're doing some stress testing around evacuating containers and finding with a large number of containers starting simultaneously, we need even more time.  We definitely need the timeout value to be configurable via a spec property in the release.

**Comment by aemengo** [comment]
Since this release rarely sees updates, we're cautious about adding new ones. Please give the following a branch a try.

If your issues are fixed with the configurable timeout below, then we'll merge and ship a new release.

https://github.com/cloudfoundry/winc-release/tree/configure-winc-network-timeout

**Comment by amhuber** [comment]
I had already tested compiling winc-network.exe with an increased hard-coded timeout and it definitely resolved our issues.  I just did a quick review of your commits in winc and winc-release and that looks like exactly what we need.

**Comment by aemengo** [comment]
I've merged in the changes and will let you know when we cut a release with these changes.

**Comment by aemengo** [comment]
This functionality has been shipped as part of [v2.3.0](https://github.com/cloudfoundry/winc-release/releases/tag/v2.3.0). Thanks for contributing!
